# Generated by Django 5.2.6 on 2025-09-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("location", models.CharField()),
                ("Current_Quantity", models.FloatField()),
                ("min_Level", models.FloatField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="In Stock", max_length=50)),
            ],
        ),
    ]
