# Generated by Django 5.2.6 on 2025-09-19 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="Current_Quantity",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="min_Level",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="name",
            field=models.CharField(
                max_length=40, validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
    ]
