# Generated by Django 5.2.6 on 2025-09-19 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0002_alter_inventory_current_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="Price",
            field=models.FloatField(
                default=5, validators=[django.core.validators.MinValueValidator(0.5)]
            ),
        ),
    ]
